### ISSUE TITLE
Modelo de dominio

### ISSUE THREAD

**Issue by julietamponti** [squad120221c/squad_1_2022_1c#5]
Link  a la imagen de modelo de dominio actual: 
https://drive.google.com/file/d/1M_RIPO4uxm9CmWbdBLYHlbgxlfIVmLb1/view?usp=sharing

**Comment by tcastellano00** [comment]
Se arma una primera versión y : 
https://drive.google.com/file/d/1pYIe0VxnOVVbXoSnk-KzzSnDGi_MkkrK/view?usp=sharing

Se asigna label para revisión
