### ISSUE TITLE
Mapa C4 Nivel I

### ISSUE THREAD

**Issue by julietamponti** [squad120221c/squad_1_2022_1c#6]
Link a la imagen del diagrama C4 nivel I:
https://drive.google.com/file/d/1XbrOIzINsvu-ILmHhkcFIRydT-w_OgLQ/view?usp=sharing&authuser=1

**Comment by tcastellano00** [comment]
Se arma una primera versión y : 
https://drive.google.com/file/d/1VeyBLZ6pvxl5zR4ODitKnzCEkWgNlqAe/view?usp=sharing

Se asigna label para revisión
